name: iRain
main: iRain\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
commands:
  ctime:
    description: "Check the time"
  cdate:
    description: "Check the date"
  ping:
    description: "Check your ping"
